
import { Investment } from './types';

export const investmentData: Investment[] = [
  {
    id: 1,
    name: "Jakarta Container #JKT001",
    containerNumber: "AKAR-JKT001",
    minAmount: 5000000,
    returnRate: 14.5,
    tokensAvailable: 10000,
    tokensSold: 7500,
    period: "12 months",
    risk: "Medium",
    location: "Jakarta, Indonesia",
    description: "Hydroponic leafy greens production facility serving high-end supermarkets in Jakarta.",
    imageUrl: "",
    status: "active",
    fundingGoal: 100000000,
    fundingProgress: 75,
    duration: 12,
    riskLevel: "medium",
    startDate: "2023-01-15",
    endDate: "2024-01-15",
    historicalReturns: [
      { month: "Jan", return: 1.2 },
      { month: "Feb", return: 1.3 },
      { month: "Mar", return: 1.1 },
      { month: "Apr", return: 1.4 },
      { month: "May", return: 1.3 },
      { month: "Jun", return: 1.2 }
    ]
  },
  {
    id: 2,
    name: "Surabaya Container #SBY002",
    containerNumber: "AKAR-SBY002",
    minAmount: 7500000,
    returnRate: 16.0,
    tokensAvailable: 12000,
    tokensSold: 9000,
    period: "12 months",
    risk: "Low",
    location: "Surabaya, Indonesia",
    description: "Vertical farming operation specializing in organic herbs for local restaurants.",
    imageUrl: "",
    status: "active",
    fundingGoal: 120000000,
    fundingProgress: 80,
    duration: 12,
    riskLevel: "low",
    startDate: "2023-02-20",
    endDate: "2024-02-20",
    historicalReturns: [
      { month: "Jan", return: 1.3 },
      { month: "Feb", return: 1.4 },
      { month: "Mar", return: 1.2 },
      { month: "Apr", return: 1.5 },
      { month: "May", return: 1.4 },
      { month: "Jun", return: 1.3 }
    ]
  },
  {
    id: 3,
    name: "Medan Container #MDN003",
    containerNumber: "AKAR-MDN003",
    minAmount: 6000000,
    returnRate: 15.0,
    tokensAvailable: 11000,
    tokensSold: 8000,
    period: "12 months",
    risk: "Medium",
    location: "Medan, Indonesia",
    description: "Specialized in exotic fruits for export to Singapore and Malaysia.",
    imageUrl: "",
    status: "active",
    fundingGoal: 110000000,
    fundingProgress: 70,
    duration: 12,
    riskLevel: "medium",
    startDate: "2023-03-10",
    endDate: "2024-03-10",
    historicalReturns: [
      { month: "Jan", return: 1.1 },
      { month: "Feb", return: 1.2 },
      { month: "Mar", return: 1.0 },
      { month: "Apr", return: 1.3 },
      { month: "May", return: 1.2 },
      { month: "Jun", return: 1.1 }
    ]
  },
  {
    id: 4,
    name: "Makassar Container #MKS004",
    containerNumber: "AKAR-MKS004",
    minAmount: 7000000,
    returnRate: 15.5,
    tokensAvailable: 13000,
    tokensSold: 10000,
    period: "12 months",
    risk: "Low",
    location: "Makassar, Indonesia",
    description: "Focusing on sustainable vegetable production for local markets.",
    imageUrl: "",
    status: "active",
    fundingGoal: 130000000,
    fundingProgress: 85,
    duration: 12,
    riskLevel: "low",
    startDate: "2023-04-01",
    endDate: "2024-04-01",
    historicalReturns: [
      { month: "Jan", return: 1.4 },
      { month: "Feb", return: 1.5 },
      { month: "Mar", return: 1.3 },
      { month: "Apr", return: 1.6 },
      { month: "May", return: 1.5 },
      { month: "Jun", return: 1.4 }
    ]
  },
  {
    id: 5,
    name: "Denpasar Container #DPS005",
    containerNumber: "AKAR-DPS005",
    minAmount: 5500000,
    returnRate: 14.0,
    tokensAvailable: 10500,
    tokensSold: 8000,
    period: "12 months",
    risk: "Medium",
    location: "Denpasar, Indonesia",
    description: "Cultivating high-demand herbs for the tourism and hospitality sector.",
    imageUrl: "",
    status: "active",
    fundingGoal: 105000000,
    fundingProgress: 72,
    duration: 12,
    riskLevel: "medium",
    startDate: "2023-05-15",
    endDate: "2024-05-15",
    historicalReturns: [
      { month: "Jan", return: 1.0 },
      { month: "Feb", return: 1.1 },
      { month: "Mar", return: 0.9 },
      { month: "Apr", return: 1.2 },
      { month: "May", return: 1.1 },
      { month: "Jun", return: 1.0 }
    ]
  }
];

export const dummyInvestment: Investment = {
  id: 1,
  name: "Jakarta Container #JKT001",
  containerNumber: "AKAR-JKT001",
  minAmount: 5000000,
  returnRate: 14.5,
  tokensAvailable: 10000,
  tokensSold: 7500,
  period: "12 months",
  risk: "Medium",
  location: "Jakarta, Indonesia",
  description: "Hydroponic leafy greens production facility serving high-end supermarkets in Jakarta.",
  imageUrl: "",
  status: "active",
  fundingGoal: 100000000,
  fundingProgress: 75,
  duration: 12,
  riskLevel: "medium",
  startDate: "2023-01-15",
  endDate: "2024-01-15",
  historicalReturns: [
    { month: "Jan", return: 1.2 },
    { month: "Feb", return: 1.3 },
    { month: "Mar", return: 1.1 },
    { month: "Apr", return: 1.4 },
    { month: "May", return: 1.3 },
    { month: "Jun", return: 1.2 }
  ]
};
